drivers: soc: atmel: fix type for same7
EXTERNAL EMAIL: Do not click links or open attachments unless you know the content is safe

From: Arnd Bergmann <arnd@arndb.de>

A missing comma caused a build failure:

drivers/soc/atmel/soc.c:196:24: error: too few arguments provided to function-like macro invocation

Fixes: af3a10513cd6 ("drivers: soc: atmel: add per soc id and version match masks")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
[claudiu.beznea@microchip.com: applied from mailing list]
Signed-off-by: Claudiu Beznea <claudiu.beznea@microchip.com>